=== hemanivetha/Mode1Training/Day24/XmlDemo/WebContent/WEB-INF/Employee.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="employee">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="emp" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>

							<xs:element name="empno">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>

							<xs:element name="name">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="([a-zA-Z])*" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>

							<xs:element name="salary" type="xs:integer" />

							<xs:element name="band">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[CME]" />
										<xs:maxLength value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>

							<xs:element name="doj">
								<xs:simpleType>
									<xs:restriction base="xs:date">
										<xs:minInclusive value="2019-09-18" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>

						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== hemanivetha/Mode1Training/Day24/XmlDemo/WebContent/WEB-INF/EmployXML.xml
<?xml version="1.0" encoding="UTF-8"?>

<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Employee.xsd">

	<emp>
		<empno>31</empno>
		<name>Madhu</name>
		<salary>15000</salary>
		<band>M</band>
		<doj>2020-05-23</doj>
	</emp>

	<emp>
		<empno>32</empno>
		<name>Soundarraj</name>
		<salary>9000</salary>
		<band>C</band>
		<doj>2020-06-17</doj>
	</emp>

	<emp>
		<empno>33</empno>
		<name>Sri</name>
		<salary>10000</salary>
		<band>E</band>
		<doj>2020-09-22</doj>
	</emp>
	
	<emp>
		<empno>34</empno>
		<name>Hema</name>
		<salary>10000</salary>
		<band>E</band>
		<doj>2020-09-22</doj>
	</emp>
	
	<emp>
		<empno>35</empno>
		<name>Shiva</name>
		<salary>10000</salary>
		<band>E</band>
		<doj>2020-09-22</doj>
	</emp>
	
	<emp>
		<empno>36</empno>
		<name>Booma</name>
		<salary>10000</salary>
		<band>E</band>
		<doj>2020-09-22</doj>
	</emp>
	
	<emp>
		<empno>37</empno>
		<name>Gayathri</name>
		<salary>10000</salary>
		<band>E</band>
		<doj>2020-09-22</doj>
	</emp>
	
	<emp>
		<empno>38</empno>
		<name>Sathish</name>
		<salary>10000</salary>
		<band>E</band>
		<doj>2020-09-22</doj>
	</emp>
	
	<emp>
		<empno>39</empno>
		<name>Dhinesh</name>
		<salary>10000</salary>
		<band>E</band>
		<doj>2020-09-22</doj>
	</emp>
	
	<emp>
		<empno>40</empno>
		<name>Keerthna</name>
		<salary>10000</salary>
		<band>E</band>
		<doj>2020-09-22</doj>
	</emp>

</employee>
